config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages
    collection do
      post :search
    end
  end
  
  # leave_room_path(room)
  get 'rooms/leave/:id', to: 'rooms#leave', as: 'leave_room'
  # join_room_path(room)
  get 'rooms/join/:id', to: 'rooms#join', as: 'join_room' 

  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'user/:id', to: 'users#show', as: 'user'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/home.html.erb
<section class="vh-100 scrollable">
  <div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-6">
        <%= image_tag "back_home.svg", class: "d-block mx-lg-auto img-fluid", width: "700", height: "500", loading: "lazy" %>
      </div>
      <div class="col-lg-6">
        <h1 class="display-2 fw-bold lh-1 mb-4">Worlds first solution for students</h1>
        <p class="lead">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start">
            <% if current_user %>
                <%= link_to "Start Chatting", rooms_path, class: 'btn gradient_btn px-4 me-md-4 mt-4'  %>
                <%= link_to "Edit Account", edit_user_registration_path, class:'btn btn-primary px-4 me-md-4 mt-4' %>
                <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary px-4 mt-4' %>
            <% else %>
                <%= link_to "Login", new_user_session_path, class: 'btn gradient_btn btn-lg px-4 me-md-4 mt-4' %>
                <%= link_to "Signup", new_user_registration_path, class: 'btn btn-primary btn-lg px-4 mt-4' %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>